### ISSUE TITLE
README.rst Usage section incorrect? (importing nerd)

### ISSUE THREAD

**Issue by rautant** [hirmeos/entity-fishing-client-python#7]
I think there is a mistake in the current README, in particular in the 'Usage' section importing nerd with
``from nerd import nerd``
produces ``ImportError: cannot import name 'nerd'``.
This works though: ``from nerd.nerd_client import NerdClient`` or ``from nerd import nerd_client``.

**Comment by lfoppiano** [comment]
Hi @rautant thanks for pointing this out. Indeed it's a mistake in the documentation.
